apiVersion: v1
kind: Pod
spec:
  containers:
    - name: kubectl
      image: lachlanevenson/k8s-kubectl
      command: ['cat']
      imagePullPolicy: Always
      tty: true
    - name: docker
      image: docker:18.06.1
      command: ['cat']
      imagePullPolicy: Always
      tty: true
      volumeMounts:
      - name: dockersock
        mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
