apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: mySA
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive
  namespace: kube-system
  apiGroup: ""
- kind: Group
  name: system:serviceaccounts
  apiGroup: ""
  namespace: staging
- kind: Group
  name: system:authenticated
  apiGroup: ""
  namespace: staging
- kind: Group
  name: system:unauthenticated
  apiGroup: ""
  namespace: staging
- kind: Group
  name: system:anonymous
  apiGroup: ""
  namespace: staging
roleRef:
  kind: ClusterRole
  name: mySA
  apiGroup: rbac.authorization.k8s.io