apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mySA
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
# These rules will be added to the "monitoring" role.
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]