---

apiVersion: - v1
kind: Pod
metadata: 
  name: web
  namespace: staging
spec:
  containers:
  - name: myweb
    image: $DOCKER_IMAGE_NAME
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  

---
apiVersion: v1
kind: Service
metadata:
  name: myweb
  namespace: staging
  labels:
    app: myweb
spec:
  type: LoadBalancer
  selector:
    app: myweb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002 