apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  labels:
    app: myweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: 187498025781.dkr.ecr.eu-west-1.amazonaws.com/docker-registry:1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
