---
apiVersion: v1
kind: Service
metadata:
  name: myweb
  labels:
    app: myweb
spec:
  type: NodePort
  selector:
    app: myweb
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32223 
    
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-web
  labels:
    app: myweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 80
